# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplate < Formula
  desc "Template"
  homepage "https://github.com/vonglasow/go-template"
  version "1.1.4"
  license "GPL3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vonglasow/go-template/releases/download/v1.1.4/template-go_1.1.4_darwin_arm64.tar.gz"
      sha256 "a99fa68c06740c1303049bef40853358c56793c12ca3424475ab4802926abb77"

      def install
        bin.install "template-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/go-template/releases/download/v1.1.4/template-go_1.1.4_darwin_amd64.tar.gz"
      sha256 "4692a306df1cbcb263a5b6b0550577deae764c464420623ef062e9eb2c818381"

      def install
        bin.install "template-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/go-template/releases/download/v1.1.4/template-go_1.1.4_linux_amd64.tar.gz"
      sha256 "585e81bcc73b147b188c316221d6ea922fc9ef9f7deb6693e3840036978cb941"

      def install
        bin.install "template-go"
      end
    end
  end
end
