# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TemplateGo < Formula
  desc "Template"
  homepage "https://github.com/vonglasow/template-go"
  version "1.1.6"
  license "GPL3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vonglasow/go-template/releases/download/v1.1.6/template-go_1.1.6_darwin_arm64.tar.gz"
      sha256 "6b0d52ecaf3525f76b2ed74475948355ba834a5f81aab5c959211b1ad2e8c364"

      def install
        bin.install "template-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/go-template/releases/download/v1.1.6/template-go_1.1.6_darwin_amd64.tar.gz"
      sha256 "7739a45a6b3b803cbf2598e9b38ba5763c96f76d0bc7dc6c061e5bd3e62b9815"

      def install
        bin.install "template-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/go-template/releases/download/v1.1.6/template-go_1.1.6_linux_amd64.tar.gz"
      sha256 "d687c056a6de8d354582dd5c4138ce9f6252a8f784f71c172f0ca4aeccab68d7"

      def install
        bin.install "template-go"
      end
    end
  end
end
