# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TemplateGo < Formula
  desc "Template"
  homepage "https://github.com/vonglasow/template-go"
  version "1.1.7"
  license "GPL3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vonglasow/template-go/releases/download/v1.1.7/template-go_1.1.7_darwin_arm64.tar.gz"
      sha256 "0464135332f9e7376f711210932dbb87d5faa7567ccd41ac94b95650a114edc0"

      def install
        bin.install "template-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/template-go/releases/download/v1.1.7/template-go_1.1.7_darwin_amd64.tar.gz"
      sha256 "77c41fe2b0ba607eda81364b612b16f8df051136ec38decc004ef92e2e12c0b3"

      def install
        bin.install "template-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/template-go/releases/download/v1.1.7/template-go_1.1.7_linux_amd64.tar.gz"
      sha256 "67b1c89d08511ef8888c23b1c0c00a6792647f0bf66037e9cc2e61158ba73adf"

      def install
        bin.install "template-go"
      end
    end
  end
end
