# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TemplateGo < Formula
  desc "Template"
  homepage "https://github.com/vonglasow/template-go"
  version "1.1.8"
  license "GPL3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vonglasow/template-go/releases/download/v1.1.8/template-go_1.1.8_darwin_arm64.tar.gz"
      sha256 "75a96d3c239693413dc7733c8c9ecb50c26bbfc1198b2e483b0bfd2ffb740533"

      def install
        bin.install "template-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/template-go/releases/download/v1.1.8/template-go_1.1.8_darwin_amd64.tar.gz"
      sha256 "ca3ffd833682d0d8bf84a4def443959f89597cb915b9e2035d7e8b25c3cbc480"

      def install
        bin.install "template-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vonglasow/template-go/releases/download/v1.1.8/template-go_1.1.8_linux_amd64.tar.gz"
      sha256 "3870746fab5b1850a7d9d1c6a0b26dbec93f047c8be43d01a32d381e53520674"

      def install
        bin.install "template-go"
      end
    end
  end
end
